# Generated by Django 2.1.7 on 2019-03-05 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CadastroCandidato',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('telefone', models.IntegerField(max_length=13)),
                ('celular', models.IntegerField(max_length=14)),
                ('email', models.EmailField(max_length=254)),
                ('endereco', models.CharField(max_length=80)),
                ('experiencia_prof', models.CharField(max_length=1000)),
            ],
        ),
    ]
