# Generated by Django 2.1.7 on 2019-03-07 01:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitedemoday', '0002_auto_20190305_1825'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidato',
            name='celular',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='candidato',
            name='telefone',
            field=models.IntegerField(),
        ),
    ]
