# Generated by Django 2.1.7 on 2019-03-07 01:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_fantasia', models.CharField(max_length=100)),
                ('razao_social', models.CharField(max_length=100)),
                ('CNPJ', models.IntegerField()),
                ('descricao_da_empresa', models.CharField(max_length=200)),
                ('porte_da_empresa', models.CharField(max_length=100)),
                ('endereco', models.CharField(max_length=100)),
                ('telefone', models.IntegerField()),
                ('email', models.EmailField(max_length=100)),
                ('site', models.CharField(max_length=100)),
                ('cargo', models.CharField(max_length=100)),
                ('descricao_da_vaga', models.CharField(max_length=300)),
                ('requisitos', models.CharField(max_length=100)),
                ('carga_horaria', models.CharField(max_length=100)),
                ('beneficios', models.CharField(max_length=100)),
                ('local_de_trabalho', models.CharField(max_length=100)),
            ],
        ),
    ]
